name: 'setup-riscv-gnu-toolchain'
description: 'Set up RISCV GNU Toolchain in your GitHub Actions workflow'
author: 'https://github.com/imkiva'
inputs:
  version:
    required: false
    default: 'latest'
    description: |
      The version of RISCV GNU Toolchain to use. You can use `latest` to get the latest version.
      All available versions can be found at [here](https://github.com/riscv-collab/riscv-gnu-toolchain/tags).

runs :
  using: 'node16'
  main: 'dist/index.js'
