name: test-setup-nightly

on:
  push:
    branches: [ main, ci ]

jobs:
  test-setup-nightly:
    name: Setup Toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Toolchain
        uses: ./
        with:
          version: '2023.09.26'
          arch: riscv64
          libc: glibc
          compiler: gcc
          os: ubuntu-22.04

      - name: Show installation directory
        run: echo $RISCV_HOME

      - name: Show sysroot directory
        run: echo $RISCV_SYSROOT

      - name: Test compilation
        run: riscv64-unknown-linux-gnu-gcc .github/main.c -o ./test

      - name: Test run
        run: qemu-riscv64 -L $RISCV_SYSROOT ./test
